package marketplace

// emit_setup.go — the ./setup launcher at the marketplace root. The marketplace is the
// standalone opencharly/marketplace repo: it pins charly in its own .gitmodules, so the
// launcher regenerates FROM the pinned checkout (`./charly`) INTO this repo (`.`) — the same
// shape the deploy workflow runs. `--check` maps to the drift gate.

const setupLauncher = "#!/usr/bin/env bash\n" +
	"# GENERATED by charly marketplace generate — DO NOT EDIT.\n" +
	"# Regenerate this marketplace from the charly checkout its .gitmodules pins:\n" +
	"#   ./setup            regenerate (charly marketplace generate --root ./charly --out .)\n" +
	"#   ./setup --check   fail-closed drift gate (regeneration must be a no-op)\n" +
	"set -euo pipefail\n" +
	"cd \"$(dirname \"$0\")\"\n" +
	"for arg in \"$@\"; do\n" +
	"    if [ \"$arg\" = \"--check\" ] || [ \"$arg\" = \"--dry-run\" ]; then\n" +
	"        exec charly marketplace drift --root ./charly --out .\n" +
	"    fi\n" +
	"done\n" +
	"exec charly marketplace generate --root ./charly --out .\n"

func emitSetup(em emissions) {
	em["plugins/setup"] = []byte(setupLauncher)
}
