package marketplace

// emit_setup.go — the plugins/setup launcher. The README documents `./setup <harness> <profile>`;
// the harness surface is now fully generated from candy config by `charly marketplace generate`,
// so the launcher is a thin forwarder preserving that CLI contract (the profile/family args no
// longer gate anything — every profile gets the same generated surface). `--check` maps to the
// drift gate.

const setupLauncher = "#!/usr/bin/env bash\n" +
	"# GENERATED by charly marketplace generate — DO NOT EDIT.\n" +
	"# Forwarding launcher preserving the README's ./setup <harness> <profile> [family] contract.\n" +
	"# The whole harness surface (skills, plugin.json, marketplace.json, profiles.json, .claude/ hooks\n" +
	"# + settings, the R0 dispatcher) is generated from candy config by 'charly marketplace generate';\n" +
	"# the profile/family selection no longer gates anything. --check runs the drift gate.\n" +
	"set -euo pipefail\n" +
	"cd \"$(dirname \"$0\")/..\"\n" +
	"for arg in \"$@\"; do\n" +
	"    if [ \"$arg\" = \"--check\" ] || [ \"$arg\" = \"--dry-run\" ]; then\n" +
	"        exec charly marketplace drift\n" +
	"    fi\n" +
	"done\n" +
	"exec charly marketplace generate\n"

func emitSetup(em emissions) {
	em["plugins/setup"] = []byte(setupLauncher)
}
