package deploypod

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/opencharly/sdk"
	"github.com/opencharly/sdk/deploykit"
	"github.com/opencharly/sdk/kit"
	"github.com/opencharly/sdk/loaderkit"
	pb "github.com/opencharly/spec/proto"
	"github.com/opencharly/spec/spec"
)

// config_setup.go — the P13-KERNEL direction-flip: sdk.OpConfigSetup. The former charly-core
// BoxConfigSetupCmd.Run/runConfig/resolveDeployRef/prepareQuadletEnv/resolveSidecars/
// runConfigDirect/parseVolumeFlags/persistResourceCaps ORCHESTRATION moved here VERBATIM in
// spirit (same sequencing, same field names — spec.PodConfigSetupRequest already carries every
// authored flag, generated by the earlier DEPLOY-wave seam). The genuinely host/loader/
// registry/credential-coupled sub-steps call back the narrow "pod-config-*" HostBuild seams
// (charly/host_build_pod_config_seams.go) — each wraps an EXISTING core function VERBATIM.

// invokeConfigSetup handles sdk.OpConfigSetup: req.ParamsJson is a #PodConfigSetupRequest.
func invokeConfigSetup(ctx context.Context, req *pb.InvokeRequest) (*pb.InvokeReply, error) {
	ex, err := sdk.ExecutorFromInvoke(req.GetExecutorBrokerId())
	if err != nil {
		return nil, fmt.Errorf("plugin-deploy-pod config-setup: executor: %w", err)
	}
	var r spec.PodConfigSetupRequest
	if err := json.Unmarshal(req.GetParamsJson(), &r); err != nil {
		return nil, fmt.Errorf("plugin-deploy-pod config-setup: decode request: %w", err)
	}
	if r.ListSidecars {
		var rep spec.PodConfigListSidecarsReply
		if err := hostBuild(ctx, ex, podConfigListSidecarsKind, spec.PodConfigLoadDeployRequest{}, &rep); err != nil {
			return nil, err
		}
		names := append([]string{}, rep.Names...)
		sort.Strings(names)
		for _, name := range names {
			fmt.Printf("%-20s %s\n", name, rep.Descriptions[name])
		}
		return marshalReply(spec.PodConfigSetupReply{})
	}
	if err := runPodConfigSetup(ctx, ex, &r); err != nil {
		return nil, err
	}
	return marshalReply(spec.PodConfigSetupReply{})
}

// hostBuild is the generic seam-call helper: marshal req, call HostBuild(kind), unmarshal into
// rep. Every "pod-config-*" seam follows this shape.
func hostBuild(ctx context.Context, ex *sdk.Executor, kind string, req, rep any) error {
	reqJSON, err := json.Marshal(req)
	if err != nil {
		return err
	}
	resJSON, err := ex.HostBuild(ctx, kind, reqJSON)
	if err != nil {
		return err
	}
	if rep == nil || len(resJSON) == 0 {
		return nil
	}
	return json.Unmarshal(resJSON, rep)
}

func runPodConfigSetup(ctx context.Context, ex *sdk.Executor, c *spec.PodConfigSetupRequest) error {
	rt, err := kit.ResolveRuntime()
	if err != nil {
		return err
	}
	switch rt.RunMode {
	case "quadlet", "direct":
	default:
		return fmt.Errorf("charly config requires run_mode=quadlet or direct (current: %s)", rt.RunMode)
	}
	if c.Box == "" {
		return fmt.Errorf("image name is required")
	}
	if spec.IsRemoteImageRef(kit.StripURLScheme(c.Box)) {
		return fmt.Errorf("remote refs are not accepted here; run 'charly box pull %s' first, then 'charly config <image-name>'", c.Box)
	}
	c.Box, c.Instance = deploykit.CanonicalizeDeployArg(c.Box, c.Instance)
	if err := deploykit.RejectImageRefAsDeployName(c.Box); err != nil {
		return err
	}
	return runConfig(ctx, ex, rt, c)
}

// resolveDeployRef mirrors the former BoxConfigSetupCmd.resolveDeployRef, resolved plugin-side
// (the "pod-config-resolve-ref" seam-collapse, #55 Cone A Unit 2 — see resolve_ref.go).
func resolveDeployRef(ctx context.Context, ex *sdk.Executor, c *spec.PodConfigSetupRequest) (deployBoxName, imageRef string, err error) {
	return resolveDeployRefLocal(ctx, ex, c.Box, c.Instance, c.Tag, c.ExplicitRef)
}

// loadDeploy reads the per-host charly.yml overlay PLUGIN-SIDE via the cycle-free
// loaderkit.LoadHostBundleConfigViaExecutor read (#55 coneC-dsh — the pod-config-load-deploy host
// seam is DELETED). caller is the warning-context tag (matching the former host leg's
// LoadDeployConfigForRead(caller) swallow): a load error degrades to (nil, nil) + a stderr warning,
// so a config setup that finds no overlay proceeds with image-label-driven behavior (the same
// graceful degradation the host leg made).
func loadDeploy(ctx context.Context, ex *sdk.Executor, caller string) (*deploykit.BundleConfig, error) {
	dc, err := loaderkit.LoadHostBundleConfigViaExecutor(ctx, ex)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Warning: %s: charly.yml unavailable for read: %v\n", caller, err)
		return nil, nil
	}
	return dc, nil
}

// saveBundle persists dc PLUGIN-SIDE via deploykit.SaveBundleConfig directly (#55 coneC-dsh — the
// pod-config-save-bundle host seam is DELETED). The marshal resugars via loader-threaded Primaries
// (deployMarshalNode) + the failsafe re-read uses the loader-backed reader (deployConfigReader), so
// the write no longer depends on the charly-init DeployStateHost registration.
//
// It is a package var (not a plain func) so resolveDeployVolumes' precedence tests can stub the
// persist leg directly (saveBundleStub, config_setup_volume_test.go) — the SAME testability pattern
// loadProjectVolume already uses. The real path drives deploykit.SaveBundleConfig (a filesystem
// write to ~/.config/charly/charly.yml) + 4 loader HostBuild seams (loader-threaded/-bootstrap/
// -walk/-materialize) via deployConfigReader/deployMarshalNode, a multi-leg path a unit test must
// not drive against the operator's real per-host overlay.
var saveBundle = func(ctx context.Context, ex *sdk.Executor, dc *deploykit.BundleConfig) error {
	return deploykit.SaveBundleConfig(dc, deployMarshalNode(ctx, ex), deployConfigReader(ctx, ex))
}

//nolint:gocyclo // ported 1:1 from charly-core BoxConfigSetupCmd.runConfig — see the file header; splitting further would fragment the seam-call sequencing across files for no clarity gain
func runConfig(ctx context.Context, ex *sdk.Executor, rt *kit.ResolvedRuntime, c *spec.PodConfigSetupRequest) error {
	var detectRep spec.PodConfigDetectDevicesReply
	if err := hostBuild(ctx, ex, podConfigDetectDevicesKind, spec.PodConfigDetectDevicesRequest{NoAutoDetect: c.NoAutoDetect}, &detectRep); err != nil {
		return err
	}
	var detected spec.DetectedDevices
	if len(detectRep.DetectedJSON) > 0 {
		if err := json.Unmarshal(detectRep.DetectedJSON, &detected); err != nil {
			return err
		}
	}

	deployBoxName, imageRef, err := resolveDeployRef(ctx, ex, c)
	if err != nil {
		return err
	}
	if err := hostBuild(ctx, ex, podConfigEnsureImageKind, spec.PodConfigEnsureImageRequest{ImageRef: imageRef, BuildEngine: rt.BuildEngine}, nil); err != nil {
		return err
	}
	// ExtractMetadata PLUGIN-SIDE (#55 coneC-dsh — the pod-config-ensure-image host seam shrinks to
	// the host-coupled ensureImagePresent leg; the deploykit label extract runs here, shedding the
	// host leg's deploykit import).
	metaPtr, err := deploykit.ExtractMetadata("podman", imageRef)
	if err != nil {
		return err
	}
	if metaPtr == nil {
		return fmt.Errorf("image %s has no embedded metadata; rebuild with latest charly", imageRef)
	}
	meta := *metaPtr

	dc, err := loadDeploy(ctx, ex, "charly config")
	if err != nil {
		return err
	}

	// Migrate plaintext env secrets + scrub CLI env credentials PLUGIN-SIDE (#55 coneC Unit C4):
	// the former HostBuild round-trip to charly's host_build_pod_config_seams.go host builders is
	// deleted; the logic relocated to secret_migration.go in this package. migrate mutates dc
	// in-place + persists via saveBundle; scrub mutates c.Env in-place. Both best-effort — matching
	// the former `err == nil` swallow (a credential-store failure keeps the plaintext/CLI value).
	_, _ = migratePlaintextEnvSecret(ctx, ex, dc, &meta, c.Box, c.Instance)
	c.Env, _ = scrubSecretCLIEnv(ctx, ex, c.Env, &meta)

	if err := persistResourceCaps(ctx, ex, &dc, c); err != nil {
		return fmt.Errorf("persisting resource caps: %w", err)
	}

	// Guard dc.Bundle (not only dc): coneC-dsh's loadDeploy → loaderkit.LoadHostBundleConfigViaExecutor
	// returns a NON-NIL &deploykit.BundleConfig{} with a nil Bundle on an absent per-host overlay
	// (the bed's XDG-isolated empty temp dir; the operator's ~/.config/charly before the first deploy
	// add) — matching deploykit.LoadBundleConfig's absent/empty contract so reap-orphans and other
	// range-without-nil-guard callers keep working. The former LoadDeployConfigForRead returned nil
	// for absent, so the pre-coneC-dsh `if dc != nil` guard skipped this block entirely (graceful
	// degradation: no overlay → no prior resolved ports → image-label defaults, meta.Port below).
	// The non-nil-&BundleConfig{} return keeps that contract for the rangers but makes `if dc != nil`
	// always true, so the guard must also check dc.Bundle: an absent overlay (nil Bundle) skips port
	// resolution — exactly the graceful degradation the loadDeploy comment names. Writing to a nil
	// Bundle here was the coneC-dsh regression (assignment-to-nil-map panic, config_setup.go:193).
	if dc != nil && dc.Bundle != nil {
		key := spec.DeployKey(c.Box, c.Instance)
		overlay := dc.Bundle[key]
		containerPorts := kit.ContainerPortsFromMappings(meta.Port)
		if len(containerPorts) > 0 || len(overlay.Port) > 0 {
			resolved, rErr := kit.ResolveDeployPorts(containerPorts, overlay.Port, overlay.ResolvedPort, deploykit.OccupiedHostPorts(dc, key))
			if rErr != nil {
				return fmt.Errorf("resolving deploy ports: %w", rErr)
			}
			if !kit.SameStringSlice(overlay.ResolvedPort, resolved) {
				overlay.ResolvedPort = resolved
				dc.Bundle[key] = overlay
				if err := saveBundle(ctx, ex, dc); err != nil {
					return fmt.Errorf("saving resolved_port: %w", err)
				}
				fmt.Fprintf(os.Stderr, "Resolved ports for %s: %s\n", key, strings.Join(resolved, ", "))
			}
		}
	}

	deploykit.MergeDeployOntoMetadata(&meta, dc, c.Box, c.Instance)

	uid, gid := meta.UID, meta.GID
	ports := meta.Port
	security := meta.Security
	network := meta.Network

	deployVolumes, err := resolveDeployVolumes(ctx, ex, c, &dc)
	if err != nil {
		return err
	}

	volumes, bindMounts := deploykit.ResolveVolumeBacking(c.Box, c.Instance, meta.Volume, deployVolumes, meta.Home, rt.EncryptedStoragePath, rt.VolumesPath)

	usingResolvedOverlay := false
	if ov, _, rerr := resolveDeployRef(ctx, ex, &spec.PodConfigSetupRequest{Box: c.Box, Instance: c.Instance}); rerr == nil {
		usingResolvedOverlay = ov != "" && ov == imageRef
	}
	if meta.Registry != "" && !kit.LooksLikeFullRef(imageRef) && c.ExplicitRef == "" && !usingResolvedOverlay {
		if _, ref, e := resolveDeployRefLocal(ctx, ex, deployBoxName, "", c.Tag, ""); e == nil {
			imageRef = ref
		}
	}

	var tunnelCfg *spec.TunnelConfig
	if meta.Tunnel != nil {
		// TunnelConfigFromMetadata PLUGIN-SIDE (#55 coneC-dsh — the pod-config-tunnel-resolve host
		// seam is DELETED; pure deploykit, no host coupling).
		if tc := deploykit.TunnelConfigFromMetadata(&meta); tc != nil {
			tunnelCfg = tc
		}
	}

	if len(c.Port) > 0 {
		var portErr error
		ports, portErr = kit.ApplyPortOverrides(ports, c.Port)
		if portErr != nil {
			return portErr
		}
	}

	portMap := deploykit.PortMapFromMappings(ports)

	// Env/MCP provides injection (P11 seam-death — see provides_inject.go). The plugin resolves the
	// provides templates itself and mutates the loaded deploy config in place, persisting through the
	// SAME loadDeploy→modify→saveBundle path the secrets/sidecar persist uses (R3); the locked
	// whole-file write + marshal resugar run plugin-side via deploykit.SaveBundleConfig (the former
	// pod-config-save-bundle host seam + the host save-callback are deleted, #55 coneC-dsh).
	dc, err = loadDeploy(ctx, ex, "charly config reload-before-inject")
	if err != nil {
		return err
	}
	provChanged := len(meta.EnvProvide) > 0 && injectEnvProvidesInto(dc, c.Box, c.Instance, meta.EnvProvide, portMap)
	if len(meta.MCPProvide) > 0 && injectMCPProvidesInto(dc, c.Box, c.Instance, meta.MCPProvide, portMap) {
		provChanged = true
	}
	if provChanged {
		if err := saveBundle(ctx, ex, dc); err != nil {
			return err
		}
	}

	if c.SshKey != "" {
		cName := kit.ContainerNameInstance(c.Box, c.Instance)
		var sshRep spec.PodConfigSSHKeyReply
		if err := hostBuild(ctx, ex, podConfigSSHKeyKind, spec.PodConfigSSHKeyRequest{Flag: c.SshKey, ContainerName: cName}, &sshRep); err != nil {
			return err
		}
		if sshRep.Pubkey != "" {
			c.Env = append(c.Env, "SSH_AUTHORIZED_KEYS="+sshRep.Pubkey)
		}
	}

	ctrName := kit.ContainerNameInstance(c.Box, c.Instance)
	acceptedEnv := deploykit.AcceptedEnvSet(meta.EnvAccept, meta.EnvRequire)
	var globalEnv []string
	if dc != nil {
		globalEnv = deploykit.GlobalEnvForImage(dc, spec.DeployKey(c.Box, c.Instance), ctrName, acceptedEnv)
	}
	envVars, envErr := kit.ResolveEnvVars(globalEnv, meta.Env, "", workspaceBindHost(bindMounts), c.EnvFile, c.Env)
	if envErr != nil {
		return envErr
	}
	var deployedNames []string
	if dc != nil {
		deployedNames = deploykit.DeployedContainerNames(dc)
	}
	envVars = kit.EnrichNoProxy(envVars, deployedNames)

	if len(meta.EnvRequire) > 0 {
		if err := checkMissingEnvRequires(c.Box, meta.EnvRequire, envVars); err != nil {
			return err
		}
	}

	quadletEnvFile := prepareQuadletEnv(c, dc, bindMounts)

	if !security.Privileged {
		security.Devices = deploykit.AppendUnique(security.Devices, detected.Devices...)
		if detected.AMDGPU {
			security.GroupAdd = appendGroupsForAMDGPU(security.GroupAdd)
		}
	}
	envVars = appendAutoDetectedEnv(envVars, detected)

	resolvedNetwork, netErr := kit.ResolveNetwork(network, rt.RunEngine)
	if netErr != nil {
		return netErr
	}

	if conflicts := kit.CheckPortAvailability(ports, rt.BindAddress, rt.RunEngine); len(conflicts) > 0 {
		fmt.Fprintf(os.Stderr, "Warning: port conflicts detected:%s", kit.FormatPortConflicts(conflicts, c.Box))
	}

	autoGen := c.Password == "auto"
	provisioned, provFallback, provResolutions, perr := resolvePodProvisionSecrets(ctx, ex, &meta, c.Box, c.Instance, rt.RunEngine, autoGen, c.RefreshSecret)
	if perr != nil {
		return perr
	}
	for _, kv := range provFallback {
		envVars = appendEnvUnique(envVars, kv)
	}
	if len(meta.SecretRequire) > 0 {
		if err := checkMissingSecretRequires(c.Box, meta.SecretRequire, provResolutions); err != nil {
			return err
		}
	}

	charlyBin := resolveHostCharlyBin(c.HostEnvJSON)

	deploySidecarsRaw := map[string]json.RawMessage{}
	if dc != nil {
		if overlay, ok := dc.Bundle[spec.DeployKey(c.Box, c.Instance)]; ok {
			deploySidecarsRaw = overlay.Sidecar
		}
	}
	for _, scName := range c.Sidecar {
		if deploySidecarsRaw == nil {
			deploySidecarsRaw = map[string]json.RawMessage{}
		}
		if _, ok := deploySidecarsRaw[scName]; !ok {
			deploySidecarsRaw[scName] = json.RawMessage("{}")
		}
	}
	var resolvedSidecars []deploykit.ResolvedSidecar
	var deploySidecars map[string]json.RawMessage
	if len(deploySidecarsRaw) > 0 {
		scRes, err := resolvePodSidecars(ctx, ex, deploySidecarsRaw, sidecarTemplatesOf(dc), c.Env, c.Box, c.Instance, rt.RunEngine, autoGen, c.RefreshSecret)
		if err != nil {
			return scErr(err)
		}
		c.Env = scRes.AppEnv
		for _, kv := range scRes.ExtraEnv {
			envVars = appendEnvUnique(envVars, kv)
		}
		deploySidecars = scRes.PersistOverrides
		resolvedSidecars = scRes.Sidecars
	}
	envVars = mergeEnvSlices(envVars, c.Env)

	podName := ""
	if len(resolvedSidecars) > 0 {
		podName = kit.PodNameInstance(c.Box, c.Instance)
	}

	encryptedMounts := deploykit.HasEncryptedBindMounts(bindMounts)
	qcfg := deploykit.QuadletConfig{
		BoxName: c.Box, ImageRef: imageRef, Home: meta.Home, Ports: ports, Volumes: volumes,
		BindMounts: bindMounts, GPU: detected.GPU, BindAddress: rt.BindAddress, Tunnel: tunnelCfg,
		UID: uid, GID: gid, Env: envVars, EnvFile: quadletEnvFile, Instance: c.Instance,
		Security: security, Network: resolvedNetwork, Status: meta.Status, Info: meta.Info,
		Entrypoint: resolveEntrypointFromMeta(&meta), Secrets: provisioned, CharlyBin: charlyBin,
		EncryptedMounts:  encryptedMounts,
		UnattendedUnlock: resolveEncUnattendedUnlock(ctx, ex, c.Box, encryptedMounts),
		PodName:          podName, Sidecar: resolvedSidecars,
	}

	if quadletEnvFile != "" {
		qcfg.Env = append([]string{}, globalEnv...)
		qcfg.Env = append(qcfg.Env, c.Env...)
		qcfg.Env = appendAutoDetectedEnv(qcfg.Env, detected)
	}

	saveInput := spec.SaveDeployStateInput{
		Ports: ports, SetPorts: len(c.Port) > 0, Env: kit.EnvPairsToMap(c.Env), CleanEnv: c.Clean,
		EnvFile: quadletEnvFile, Network: resolvedNetwork, Security: &security, Volume: deployVolumes,
		Sidecar: deploySidecars, Tunnel: meta.Tunnel, SecretNames: secretDepNames(&meta),
		Box: deployBoxName, Target: "pod",
	}
	// #55 K4: write deploy-state PLUGIN-SIDE (deploykit.SaveDeployState via the generic loader-threaded
	// Primaries leg + loadDeploy reader), not over the deleted "deploy-config-save-state" host seam.
	deploySaveState(ctx, ex, c.Box, c.Instance, saveInput)

	if rt.RunMode == "direct" {
		return runConfigDirect(qcfg, bindMounts, resolvedSidecars, tunnelCfg)
	}

	qdir, err := kit.QuadletDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(qdir, 0755); err != nil {
		return fmt.Errorf("creating quadlet directory: %w", err)
	}
	writeReq := spec.PodConfigWriteRequest{ContainerPath: filepath.Join(qdir, kit.QuadletFilenameInstance(c.Box, c.Instance))}
	if len(resolvedSidecars) > 0 {
		writeReq.PodPath = filepath.Join(qdir, kit.PodQuadletFilenameInstance(c.Box, c.Instance))
		writeReq.SidecarPaths = make(map[string]string, len(resolvedSidecars))
		for _, sc := range resolvedSidecars {
			writeReq.SidecarPaths[sc.Name] = filepath.Join(qdir, kit.SidecarQuadletFilenameInstance(c.Box, c.Instance, sc.Name))
		}
	}
	if tunnelCfg != nil && tunnelCfg.Provider == "cloudflare" {
		svcDir, err := kit.SystemdUserDir()
		if err != nil {
			return err
		}
		if err := os.MkdirAll(svcDir, 0755); err != nil {
			return fmt.Errorf("creating systemd user directory: %w", err)
		}
		writeReq.TunnelPath = filepath.Join(svcDir, deploykit.TunnelServiceFilename(c.Box))
		writeReq.CloudflaredCfgPath = tunnelConfigPath(tunnelCfg.TunnelName)
	}
	qcfgJSON, err := json.Marshal(qcfg)
	if err != nil {
		return fmt.Errorf("marshaling pod config for write: %w", err)
	}
	writeReq.PodConfigJSON = qcfgJSON
	writeReply, err := podConfigWriteSelf(writeReq)
	if err != nil {
		return fmt.Errorf("writing pod config files: %w", err)
	}
	for _, p := range writeReply.WrittenPaths {
		fmt.Fprintf(os.Stderr, "Wrote %s\n", p)
	}

	if tunnelCfg != nil && tunnelCfg.Provider == "cloudflare" {
		if terr := podTunnelOp(ctx, ex, "setup", tunnelCfg); terr != nil {
			fmt.Fprintf(os.Stderr, "Warning: tunnel setup failed: %v\n", terr)
		}
	}

	if svcDir, svcErr := kit.SystemdUserDir(); svcErr == nil {
		encPath := filepath.Join(svcDir, kit.ContainerName(c.Box)+"-enc.service")
		if _, statErr := os.Stat(encPath); statErr == nil {
			_ = os.Remove(encPath)
			fmt.Fprintf(os.Stderr, "Removed stale %s\n", encPath)
		}
	}

	reloadCmd := exec.Command("systemctl", "--user", "daemon-reload")
	if output, err := reloadCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl daemon-reload failed: %w\n%s", err, strings.TrimSpace(string(output)))
	}
	fmt.Fprintf(os.Stderr, "Reloaded systemd user daemon\n")

	if tunnelCfg != nil && tunnelCfg.Provider == "cloudflare" {
		enableCmd := exec.Command("systemctl", "--user", "enable", deploykit.TunnelServiceFilename(c.Box))
		if output, err := enableCmd.CombinedOutput(); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: could not enable tunnel service: %v\n%s", err, strings.TrimSpace(string(output)))
		}
	}

	if deploykit.HasEncryptedBindMounts(bindMounts) {
		// Config-setup drives verb:enc DIRECTLY via InvokeProvider — the SAME plan-builders
		// (resolvePodEncEnsurePlan/resolvePodEncUnmountPlan) + InvokeProvider(verb:enc) the
		// START/STOP lifecycle path in resolve.go already uses (the retired pod-config-enc-mounts
		// seam's byte-exact parity: ensure with autoGen, then unmount unless KeepMounted).
		ensureJSON, encErr := resolvePodEncEnsurePlan(ctx, ex, dc, c.Box, c.Instance, autoGen)
		if encErr != nil {
			return fmt.Errorf("setting up encrypted volumes: %w", encErr)
		}
		if len(ensureJSON) > 0 {
			if _, err := ex.InvokeProvider(ctx, "verb", "enc", sdk.OpExecute, ensureJSON, nil, sdk.InvokeProviderOpts{}); err != nil {
				return fmt.Errorf("setting up encrypted volumes: %w", err)
			}
		}
		if !c.KeepMounted {
			unmountJSON, unErr := resolvePodEncUnmountPlan(dc, c.Box, c.Instance)
			if unErr != nil {
				return fmt.Errorf("unmounting encrypted volumes: %w", unErr)
			}
			if len(unmountJSON) > 0 {
				if _, err := ex.InvokeProvider(ctx, "verb", "enc", sdk.OpExecute, unmountJSON, nil, sdk.InvokeProviderOpts{}); err != nil {
					return fmt.Errorf("unmounting encrypted volumes: %w", err)
				}
			}
		}
	}

	dc, err = loadDeploy(ctx, ex, "charly config reload-after-volumes")
	if err != nil {
		return err
	}

	if c.Seed && (len(bindMounts) > 0 || len(volumes) > 0) {
		if err := provisionData(ctx, ex, rt, c, &meta, imageRef, dc, bindMounts, volumes, deployVolumes); err != nil {
			return err
		}
	}

	hooks := meta.Hook
	if hooks != nil && hooks.PostEnable != "" {
		svc := kit.ServiceNameInstance(c.Box, c.Instance)
		start := exec.Command("systemctl", "--user", "start", svc)
		start.Stdout = os.Stderr
		start.Stderr = os.Stderr
		if err := start.Run(); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: failed to start %s for post_enable hook: %v\n", svc, err)
		} else {
			engine := kit.EngineBinary(rt.RunEngine)
			hookSecretEnv := resolvePodHookSecretEnv(ctx, ex, &meta, c.Box, c.Instance)
			hookEnv := append(append([]string{}, c.Env...), hookSecretEnv...)
			if err := runHook(engine, ctrName, hooks.PostEnable, hookEnv); err != nil {
				fmt.Fprintf(os.Stderr, "Warning: post_enable hook failed: %v\n", err)
			}
		}
	}

	if c.UpdateAll {
		if err := updateAllDeployedQuadlets(ctx, ex, rt, spec.DeployKey(c.Box, c.Instance), charlyBin); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: could not update all quadlets: %v\n", err)
		}
	}

	if len(meta.MCPRequire) > 0 {
		reDc, _ := loadDeploy(ctx, ex, "charly config mcp_requires check")
		var mcpServers []spec.MCPProvideEntry
		if reDc != nil && reDc.Provides != nil {
			mcpServers = spec.PodAwareMCPProvides(reDc.Provides.MCP, spec.DeployKey(c.Box, c.Instance), kit.ContainerNameInstance(c.Box, c.Instance))
		}
		warnMissingMCPRequires(c.Box, meta.MCPRequire, mcpServers)
	}

	return nil
}

func scErr(err error) error { return fmt.Errorf("resolving sidecars: %w", err) }

// mergeEnvSlices appends src entries not already present by KEY in dst (last-wins on key, matching
// the former in-place c.Env reassignment semantics for the sidecar-routed app env).
func mergeEnvSlices(dst, src []string) []string {
	seen := make(map[string]bool, len(dst))
	for _, kv := range dst {
		if k, _, ok := strings.Cut(kv, "="); ok {
			seen[k] = true
		}
	}
	for _, kv := range src {
		k, _, ok := strings.Cut(kv, "=")
		if ok && seen[k] {
			continue
		}
		dst = append(dst, kv)
	}
	return dst
}
