package deploypod

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/opencharly/sdk"
	"github.com/opencharly/sdk/deploykit"
	"github.com/opencharly/sdk/kit"
	pb "github.com/opencharly/sdk/proto"
	"github.com/opencharly/sdk/spec"
)

// config_setup.go — the P13-KERNEL direction-flip: sdk.OpConfigSetup. The former charly-core
// BoxConfigSetupCmd.Run/runConfig/resolveDeployRef/prepareQuadletEnv/resolveSidecars/
// runConfigDirect/parseVolumeFlags/persistResourceCaps ORCHESTRATION moved here VERBATIM in
// spirit (same sequencing, same field names — spec.PodConfigSetupRequest already carries every
// authored flag, generated by the earlier DEPLOY-wave seam). The genuinely host/loader/
// registry/credential-coupled sub-steps call back the narrow "pod-config-*" HostBuild seams
// (charly/host_build_pod_config_seams.go) — each wraps an EXISTING core function VERBATIM.

// invokeConfigSetup handles sdk.OpConfigSetup: req.ParamsJson is a #PodConfigSetupRequest.
func invokeConfigSetup(ctx context.Context, req *pb.InvokeRequest) (*pb.InvokeReply, error) {
	ex, err := sdk.ExecutorFromInvoke(req.GetExecutorBrokerId())
	if err != nil {
		return nil, fmt.Errorf("plugin-deploy-pod config-setup: executor: %w", err)
	}
	var r spec.PodConfigSetupRequest
	if err := json.Unmarshal(req.GetParamsJson(), &r); err != nil {
		return nil, fmt.Errorf("plugin-deploy-pod config-setup: decode request: %w", err)
	}
	if r.ListSidecars {
		var rep spec.PodConfigListSidecarsReply
		if err := hostBuild(ctx, ex, podConfigListSidecarsKind, spec.PodConfigLoadDeployRequest{}, &rep); err != nil {
			return nil, err
		}
		names := append([]string{}, rep.Names...)
		sort.Strings(names)
		for _, name := range names {
			fmt.Printf("%-20s %s\n", name, rep.Descriptions[name])
		}
		return marshalReply(spec.PodConfigSetupReply{})
	}
	if err := runPodConfigSetup(ctx, ex, &r); err != nil {
		return nil, err
	}
	return marshalReply(spec.PodConfigSetupReply{})
}

// hostBuild is the generic seam-call helper: marshal req, call HostBuild(kind), unmarshal into
// rep. Every "pod-config-*" seam follows this shape.
func hostBuild(ctx context.Context, ex *sdk.Executor, kind string, req, rep any) error {
	reqJSON, err := json.Marshal(req)
	if err != nil {
		return err
	}
	resJSON, err := ex.HostBuild(ctx, kind, reqJSON)
	if err != nil {
		return err
	}
	if rep == nil || len(resJSON) == 0 {
		return nil
	}
	return json.Unmarshal(resJSON, rep)
}

func runPodConfigSetup(ctx context.Context, ex *sdk.Executor, c *spec.PodConfigSetupRequest) error {
	rt, err := kit.ResolveRuntime()
	if err != nil {
		return err
	}
	switch rt.RunMode {
	case "quadlet", "direct":
	default:
		return fmt.Errorf("charly config requires run_mode=quadlet or direct (current: %s)", rt.RunMode)
	}
	if c.Box == "" {
		return fmt.Errorf("image name is required")
	}
	if spec.IsRemoteImageRef(kit.StripURLScheme(c.Box)) {
		return fmt.Errorf("remote refs are not accepted here; run 'charly box pull %s' first, then 'charly config <image-name>'", c.Box)
	}
	c.Box, c.Instance = deploykit.CanonicalizeDeployArg(c.Box, c.Instance)
	if err := deploykit.RejectImageRefAsDeployName(c.Box); err != nil {
		return err
	}
	return runConfig(ctx, ex, rt, c)
}

// resolveDeployRef mirrors the former BoxConfigSetupCmd.resolveDeployRef via the
// "pod-config-resolve-ref" seam (loader + local podman-store coupled).
func resolveDeployRef(ctx context.Context, ex *sdk.Executor, c *spec.PodConfigSetupRequest) (deployBoxName, imageRef string, err error) {
	var rep spec.PodConfigResolveRefReply
	err = hostBuild(ctx, ex, podConfigResolveRefKind, spec.PodConfigResolveRefRequest{
		Box: c.Box, Instance: c.Instance, Tag: c.Tag, ExplicitRef: c.ExplicitRef,
	}, &rep)
	return rep.DeployBoxName, rep.ImageRef, err
}

func loadDeploy(ctx context.Context, ex *sdk.Executor, caller string) (*deploykit.BundleConfig, error) {
	var rep spec.PodConfigLoadDeployReply
	if err := hostBuild(ctx, ex, podConfigLoadDeployKind, spec.PodConfigLoadDeployRequest{Caller: caller}, &rep); err != nil {
		return nil, err
	}
	if len(rep.ConfigJSON) == 0 {
		return nil, nil
	}
	var dc deploykit.BundleConfig
	if err := json.Unmarshal(rep.ConfigJSON, &dc); err != nil {
		return nil, err
	}
	return &dc, nil
}

func saveBundle(ctx context.Context, ex *sdk.Executor, dc *deploykit.BundleConfig) error {
	b, err := json.Marshal(dc)
	if err != nil {
		return err
	}
	return hostBuild(ctx, ex, podConfigSaveBundleKind, spec.PodConfigSaveBundleRequest{ConfigJSON: b}, nil)
}

//nolint:gocyclo // ported 1:1 from charly-core BoxConfigSetupCmd.runConfig — see the file header; splitting further would fragment the seam-call sequencing across files for no clarity gain
func runConfig(ctx context.Context, ex *sdk.Executor, rt *kit.ResolvedRuntime, c *spec.PodConfigSetupRequest) error {
	var detectRep spec.PodConfigDetectDevicesReply
	if err := hostBuild(ctx, ex, podConfigDetectDevicesKind, spec.PodConfigDetectDevicesRequest{NoAutoDetect: c.NoAutoDetect}, &detectRep); err != nil {
		return err
	}
	var detected spec.DetectedDevices
	if len(detectRep.DetectedJSON) > 0 {
		if err := json.Unmarshal(detectRep.DetectedJSON, &detected); err != nil {
			return err
		}
	}

	deployBoxName, imageRef, err := resolveDeployRef(ctx, ex, c)
	if err != nil {
		return err
	}
	var ensureRep spec.PodConfigEnsureImageReply
	if err := hostBuild(ctx, ex, podConfigEnsureImageKind, spec.PodConfigEnsureImageRequest{ImageRef: imageRef, BuildEngine: rt.BuildEngine}, &ensureRep); err != nil {
		return err
	}
	var meta spec.BoxMetadata
	if err := json.Unmarshal(ensureRep.MetaJSON, &meta); err != nil {
		return err
	}

	dc, err := loadDeploy(ctx, ex, "charly config")
	if err != nil {
		return err
	}

	var migRep spec.PodConfigMigrateSecretsReply
	dcJSON, _ := json.Marshal(dc)
	if err := hostBuild(ctx, ex, podConfigMigrateSecretsKind, spec.PodConfigMigrateSecretsRequest{
		ConfigJSON: dcJSON, MetaJSON: ensureRep.MetaJSON, Box: c.Box, Instance: c.Instance,
	}, &migRep); err == nil && len(migRep.ConfigJSON) > 0 {
		// A partial/failed decode here would leave dc a hybrid of the pre- and post-migration shape
		// (json.Unmarshal can populate fields before erroring) — never silently discarded.
		if err := json.Unmarshal(migRep.ConfigJSON, &dc); err != nil {
			return fmt.Errorf("decoding migrated deploy config: %w", err)
		}
	}

	var scrubRep spec.PodConfigScrubCliEnvReply
	if err := hostBuild(ctx, ex, podConfigScrubCliEnvKind, spec.PodConfigScrubCliEnvRequest{
		CliEnv: c.Env, MetaJSON: ensureRep.MetaJSON,
	}, &scrubRep); err == nil {
		c.Env = scrubRep.Cleaned
	}

	if err := persistResourceCaps(ctx, ex, &dc, c); err != nil {
		return fmt.Errorf("persisting resource caps: %w", err)
	}

	if dc != nil {
		key := deploykit.DeployKey(c.Box, c.Instance)
		overlay := dc.Bundle[key]
		containerPorts := kit.ContainerPortsFromMappings(meta.Port)
		if len(containerPorts) > 0 || len(overlay.Port) > 0 {
			resolved, rErr := kit.ResolveDeployPorts(containerPorts, overlay.Port, overlay.ResolvedPort, dc.OccupiedHostPorts(key))
			if rErr != nil {
				return fmt.Errorf("resolving deploy ports: %w", rErr)
			}
			if !kit.SameStringSlice(overlay.ResolvedPort, resolved) {
				overlay.ResolvedPort = resolved
				dc.Bundle[key] = overlay
				if err := saveBundle(ctx, ex, dc); err != nil {
					return fmt.Errorf("saving resolved_port: %w", err)
				}
				fmt.Fprintf(os.Stderr, "Resolved ports for %s: %s\n", key, strings.Join(resolved, ", "))
			}
		}
	}

	deploykit.MergeDeployOntoMetadata(&meta, dc, c.Box, c.Instance)

	uid, gid := meta.UID, meta.GID
	ports := meta.Port
	security := meta.Security
	network := meta.Network

	deployVolumes, err := resolveDeployVolumes(ctx, ex, c, &dc)
	if err != nil {
		return err
	}

	volumes, bindMounts := deploykit.ResolveVolumeBacking(c.Box, c.Instance, meta.Volume, deployVolumes, meta.Home, rt.EncryptedStoragePath, rt.VolumesPath)

	usingResolvedOverlay := false
	if ov, _, rerr := resolveDeployRef(ctx, ex, &spec.PodConfigSetupRequest{Box: c.Box, Instance: c.Instance}); rerr == nil {
		usingResolvedOverlay = ov != "" && ov == imageRef
	}
	if meta.Registry != "" && !kit.LooksLikeFullRef(imageRef) && c.ExplicitRef == "" && !usingResolvedOverlay {
		var rep spec.PodConfigResolveRefReply
		if err := hostBuild(ctx, ex, podConfigResolveRefKind, spec.PodConfigResolveRefRequest{
			Box: deployBoxName, Instance: "", Tag: c.Tag,
		}, &rep); err == nil {
			imageRef = rep.ImageRef
		}
	}

	var tunnelCfg *spec.TunnelConfig
	if meta.Tunnel != nil {
		var tRep spec.PodConfigTunnelResolveReply
		if err := hostBuild(ctx, ex, podConfigTunnelResolveKind, spec.PodConfigTunnelResolveRequest(ensureRep), &tRep); err == nil && len(tRep.TunnelJSON) > 0 {
			var tc spec.TunnelConfig
			if json.Unmarshal(tRep.TunnelJSON, &tc) == nil {
				tunnelCfg = &tc
			}
		}
	}

	if len(c.Port) > 0 {
		var portErr error
		ports, portErr = kit.ApplyPortOverrides(ports, c.Port)
		if portErr != nil {
			return portErr
		}
	}

	portMap := deploykit.PortMapFromMappings(ports)
	portMapJSON, _ := json.Marshal(portMap)

	if len(meta.EnvProvide) > 0 {
		_ = hostBuild(ctx, ex, podConfigInjectEnvKind, spec.PodConfigInjectEnvProvidesRequest{
			Box: c.Box, Instance: c.Instance, EnvProvides: meta.EnvProvide, PortMapJSON: portMapJSON,
		}, nil)
	}
	if len(meta.MCPProvide) > 0 {
		mcpJSON, _ := json.Marshal(meta.MCPProvide)
		_ = hostBuild(ctx, ex, podConfigInjectMCPKind, spec.PodConfigInjectMCPProvidesRequest{
			Box: c.Box, Instance: c.Instance, MCPProvidesJSON: mcpJSON, PortMapJSON: portMapJSON,
		}, nil)
	}
	dc, err = loadDeploy(ctx, ex, "charly config reload-after-inject")
	if err != nil {
		return err
	}

	if c.SshKey != "" {
		cName := kit.ContainerNameInstance(c.Box, c.Instance)
		var sshRep spec.PodConfigSSHKeyReply
		if err := hostBuild(ctx, ex, podConfigSSHKeyKind, spec.PodConfigSSHKeyRequest{Flag: c.SshKey, ContainerName: cName}, &sshRep); err != nil {
			return err
		}
		if sshRep.Pubkey != "" {
			c.Env = append(c.Env, "SSH_AUTHORIZED_KEYS="+sshRep.Pubkey)
		}
	}

	ctrName := kit.ContainerNameInstance(c.Box, c.Instance)
	acceptedEnv := deploykit.AcceptedEnvSet(meta.EnvAccept, meta.EnvRequire)
	var globalEnv []string
	if dc != nil {
		globalEnv = dc.GlobalEnvForImage(deploykit.DeployKey(c.Box, c.Instance), ctrName, acceptedEnv)
	}
	envVars, envErr := kit.ResolveEnvVars(globalEnv, meta.Env, "", workspaceBindHost(bindMounts), c.EnvFile, c.Env)
	if envErr != nil {
		return envErr
	}
	var deployedNames []string
	if dc != nil {
		deployedNames = dc.DeployedContainerNames()
	}
	envVars = kit.EnrichNoProxy(envVars, deployedNames)

	if len(meta.EnvRequire) > 0 {
		if err := checkMissingEnvRequires(c.Box, meta.EnvRequire, envVars); err != nil {
			return err
		}
	}

	quadletEnvFile := prepareQuadletEnv(c, dc, bindMounts)

	if !security.Privileged {
		security.Devices = deploykit.AppendUnique(security.Devices, detected.Devices...)
		if detected.AMDGPU {
			security.GroupAdd = appendGroupsForAMDGPU(security.GroupAdd)
		}
	}
	envVars = appendAutoDetectedEnv(envVars, detected)

	resolvedNetwork, netErr := kit.ResolveNetwork(network, rt.RunEngine)
	if netErr != nil {
		return netErr
	}

	if conflicts := kit.CheckPortAvailability(ports, rt.BindAddress, rt.RunEngine); len(conflicts) > 0 {
		fmt.Fprintf(os.Stderr, "Warning: port conflicts detected:%s", kit.FormatPortConflicts(conflicts, c.Box))
	}

	var provRep spec.PodConfigProvisionSecretsReply
	autoGen := c.Password == "auto"
	if err := hostBuild(ctx, ex, podConfigProvisionSecretsKind, spec.PodConfigProvisionSecretsRequest{
		MetaJSON: ensureRep.MetaJSON, Box: c.Box, Instance: c.Instance, RunEngine: rt.RunEngine,
		AutoGen: autoGen, RefreshSecret: c.RefreshSecret,
	}, &provRep); err != nil {
		return err
	}
	var provisioned []deploykit.CollectedSecret
	if len(provRep.ProvisionedJSON) > 0 {
		if err := json.Unmarshal(provRep.ProvisionedJSON, &provisioned); err != nil {
			return fmt.Errorf("decoding provisioned secrets: %w", err)
		}
	}
	for _, kv := range provRep.FallbackEnv {
		envVars = appendEnvUnique(envVars, kv)
	}
	if len(meta.SecretRequire) > 0 {
		var resolutions []secretResolution
		if len(provRep.ResolutionsJSON) > 0 {
			// A silently-discarded decode failure here would make checkMissingSecretRequires evaluate
			// against an EMPTY resolutions list — indistinguishable from "nothing resolved yet" — and
			// wrongly report every secret_require as missing, or worse, wrongly pass a genuinely-unmet
			// requirement if the zero-value happens to satisfy the check.
			if err := json.Unmarshal(provRep.ResolutionsJSON, &resolutions); err != nil {
				return fmt.Errorf("decoding secret resolutions: %w", err)
			}
		}
		if err := checkMissingSecretRequires(c.Box, meta.SecretRequire, resolutions); err != nil {
			return err
		}
	}

	charlyBin := resolveHostCharlyBin(c.HostEnvJSON)
	isKeyring := provRep.IsKeyring

	var sidecarRep spec.PodConfigResolveSidecarsReply
	deploySidecarsRaw := map[string]json.RawMessage{}
	if dc != nil {
		if overlay, ok := dc.Bundle[deploykit.DeployKey(c.Box, c.Instance)]; ok {
			deploySidecarsRaw = overlay.Sidecar
		}
	}
	for _, scName := range c.Sidecar {
		if deploySidecarsRaw == nil {
			deploySidecarsRaw = map[string]json.RawMessage{}
		}
		if _, ok := deploySidecarsRaw[scName]; !ok {
			deploySidecarsRaw[scName] = json.RawMessage("{}")
		}
	}
	var resolvedSidecars []deploykit.ResolvedSidecar
	var deploySidecars map[string]json.RawMessage
	if len(deploySidecarsRaw) > 0 {
		dsJSON, _ := json.Marshal(deploySidecarsRaw)
		ptJSON, _ := json.Marshal(sidecarTemplatesOf(dc))
		if err := hostBuild(ctx, ex, podConfigResolveSidecarsKind, spec.PodConfigResolveSidecarsRequest{
			DeploySidecarsJSON: dsJSON, ProjectTemplatesJSON: ptJSON, CliEnv: c.Env,
			Box: c.Box, Instance: c.Instance, RunEngine: rt.RunEngine, AutoGen: autoGen,
			RefreshSecret: c.RefreshSecret,
		}, &sidecarRep); err != nil {
			return scErr(err)
		}
		c.Env = sidecarRep.AppEnv
		for _, kv := range sidecarRep.ExtraEnv {
			envVars = appendEnvUnique(envVars, kv)
		}
		if len(sidecarRep.PersistOverridesJSON) > 0 {
			if err := json.Unmarshal(sidecarRep.PersistOverridesJSON, &deploySidecars); err != nil {
				return fmt.Errorf("decoding sidecar persist overrides: %w", err)
			}
		}
		if len(sidecarRep.ResolvedSidecarsJSON) > 0 {
			if err := json.Unmarshal(sidecarRep.ResolvedSidecarsJSON, &resolvedSidecars); err != nil {
				return fmt.Errorf("decoding resolved sidecars: %w", err)
			}
		}
	}
	envVars = mergeEnvSlices(envVars, c.Env)

	podName := ""
	if len(resolvedSidecars) > 0 {
		podName = kit.PodNameInstance(c.Box, c.Instance)
	}

	qcfg := deploykit.QuadletConfig{
		BoxName: c.Box, ImageRef: imageRef, Home: meta.Home, Ports: ports, Volumes: volumes,
		BindMounts: bindMounts, GPU: detected.GPU, BindAddress: rt.BindAddress, Tunnel: tunnelCfg,
		UID: uid, GID: gid, Env: envVars, EnvFile: quadletEnvFile, Instance: c.Instance,
		Security: security, Network: resolvedNetwork, Status: meta.Status, Info: meta.Info,
		Entrypoint: resolveEntrypointFromMeta(&meta), Secrets: provisioned, CharlyBin: charlyBin,
		EncryptedMounts: deploykit.HasEncryptedBindMounts(bindMounts), KeyringBackend: isKeyring,
		PodName: podName, Sidecar: resolvedSidecars,
	}

	if quadletEnvFile != "" {
		qcfg.Env = append([]string{}, globalEnv...)
		qcfg.Env = append(qcfg.Env, c.Env...)
		qcfg.Env = appendAutoDetectedEnv(qcfg.Env, detected)
	}

	saveInput := deploykit.SaveDeployStateInput{
		Ports: ports, SetPorts: len(c.Port) > 0, Env: kit.EnvPairsToMap(c.Env), CleanEnv: c.Clean,
		EnvFile: quadletEnvFile, Network: resolvedNetwork, Security: &security, Volume: deployVolumes,
		Sidecar: deploySidecars, Tunnel: meta.Tunnel, SecretNames: secretDepNames(&meta),
		Box: deployBoxName, Target: "pod",
	}
	inputJSON, _ := json.Marshal(saveInput)
	if err := hostBuild(ctx, ex, deployConfigSaveStateKind, spec.DeployConfigSaveStateRequest{
		Box: c.Box, Instance: c.Instance, InputJSON: inputJSON,
	}, nil); err != nil {
		return err
	}

	if rt.RunMode == "direct" {
		return runConfigDirect(qcfg, bindMounts, resolvedSidecars, tunnelCfg)
	}

	qdir, err := kit.QuadletDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(qdir, 0755); err != nil {
		return fmt.Errorf("creating quadlet directory: %w", err)
	}
	writeReq := spec.PodConfigWriteRequest{ContainerPath: filepath.Join(qdir, kit.QuadletFilenameInstance(c.Box, c.Instance))}
	if len(resolvedSidecars) > 0 {
		writeReq.PodPath = filepath.Join(qdir, kit.PodQuadletFilenameInstance(c.Box, c.Instance))
		writeReq.SidecarPaths = make(map[string]string, len(resolvedSidecars))
		for _, sc := range resolvedSidecars {
			writeReq.SidecarPaths[sc.Name] = filepath.Join(qdir, kit.SidecarQuadletFilenameInstance(c.Box, c.Instance, sc.Name))
		}
	}
	if tunnelCfg != nil && tunnelCfg.Provider == "cloudflare" {
		svcDir, err := kit.SystemdUserDir()
		if err != nil {
			return err
		}
		if err := os.MkdirAll(svcDir, 0755); err != nil {
			return fmt.Errorf("creating systemd user directory: %w", err)
		}
		writeReq.TunnelPath = filepath.Join(svcDir, deploykit.TunnelServiceFilename(c.Box))
		writeReq.CloudflaredCfgPath = tunnelConfigPath(tunnelCfg.TunnelName)
	}
	qcfgJSON, err := json.Marshal(qcfg)
	if err != nil {
		return fmt.Errorf("marshaling pod config for write: %w", err)
	}
	writeReq.PodConfigJSON = qcfgJSON
	writeReply, err := podConfigWriteSelf(writeReq)
	if err != nil {
		return fmt.Errorf("writing pod config files: %w", err)
	}
	for _, p := range writeReply.WrittenPaths {
		fmt.Fprintf(os.Stderr, "Wrote %s\n", p)
	}

	if tunnelCfg != nil && tunnelCfg.Provider == "cloudflare" {
		if terr := podTunnelOp(ctx, ex, "setup", tunnelCfg); terr != nil {
			fmt.Fprintf(os.Stderr, "Warning: tunnel setup failed: %v\n", terr)
		}
	}

	if svcDir, svcErr := kit.SystemdUserDir(); svcErr == nil {
		encPath := filepath.Join(svcDir, kit.ContainerName(c.Box)+"-enc.service")
		if _, statErr := os.Stat(encPath); statErr == nil {
			_ = os.Remove(encPath)
			fmt.Fprintf(os.Stderr, "Removed stale %s\n", encPath)
		}
	}

	reloadCmd := exec.Command("systemctl", "--user", "daemon-reload")
	if output, err := reloadCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl daemon-reload failed: %w\n%s", err, strings.TrimSpace(string(output)))
	}
	fmt.Fprintf(os.Stderr, "Reloaded systemd user daemon\n")

	if tunnelCfg != nil && tunnelCfg.Provider == "cloudflare" {
		enableCmd := exec.Command("systemctl", "--user", "enable", deploykit.TunnelServiceFilename(c.Box))
		if output, err := enableCmd.CombinedOutput(); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: could not enable tunnel service: %v\n%s", err, strings.TrimSpace(string(output)))
		}
	}

	if deploykit.HasEncryptedBindMounts(bindMounts) {
		if err := hostBuild(ctx, ex, podConfigEncMountsKind, spec.PodConfigEncMountsRequest{
			Box: c.Box, Instance: c.Instance, AutoGen: autoGen, KeepMounted: c.KeepMounted,
		}, nil); err != nil {
			return fmt.Errorf("setting up encrypted volumes: %w", err)
		}
	}

	dc, err = loadDeploy(ctx, ex, "charly config reload-after-volumes")
	if err != nil {
		return err
	}

	if c.Seed && (len(bindMounts) > 0 || len(volumes) > 0) {
		if err := provisionData(ctx, ex, rt, c, &meta, imageRef, dc, bindMounts, volumes, deployVolumes); err != nil {
			return err
		}
	}

	hooks := meta.Hook
	if hooks != nil && hooks.PostEnable != "" {
		svc := kit.ServiceNameInstance(c.Box, c.Instance)
		start := exec.Command("systemctl", "--user", "start", svc)
		start.Stdout = os.Stderr
		start.Stderr = os.Stderr
		if err := start.Run(); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: failed to start %s for post_enable hook: %v\n", svc, err)
		} else {
			engine := kit.EngineBinary(rt.RunEngine)
			var hookRep spec.PodConfigHookSecretEnvReply
			_ = hostBuild(ctx, ex, podConfigHookSecretEnvKind, spec.PodConfigHookSecretEnvRequest{
				Box: c.Box, Instance: c.Instance, MetaJSON: ensureRep.MetaJSON,
			}, &hookRep)
			hookEnv := append(append([]string{}, c.Env...), hookRep.Env...)
			if err := runHook(engine, ctrName, hooks.PostEnable, hookEnv); err != nil {
				fmt.Fprintf(os.Stderr, "Warning: post_enable hook failed: %v\n", err)
			}
		}
	}

	if c.UpdateAll {
		if err := updateAllDeployedQuadlets(ctx, ex, rt, deploykit.DeployKey(c.Box, c.Instance), charlyBin); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: could not update all quadlets: %v\n", err)
		}
	}

	if len(meta.MCPRequire) > 0 {
		reDc, _ := loadDeploy(ctx, ex, "charly config mcp_requires check")
		var mcpServers []spec.MCPProvideEntry
		if reDc != nil && reDc.Provides != nil {
			mcpServers = spec.PodAwareMCPProvides(reDc.Provides.MCP, deploykit.DeployKey(c.Box, c.Instance), kit.ContainerNameInstance(c.Box, c.Instance))
		}
		warnMissingMCPRequires(c.Box, meta.MCPRequire, mcpServers)
	}

	return nil
}

func scErr(err error) error { return fmt.Errorf("resolving sidecars: %w", err) }

// mergeEnvSlices appends src entries not already present by KEY in dst (last-wins on key, matching
// the former in-place c.Env reassignment semantics for the sidecar-routed app env).
func mergeEnvSlices(dst, src []string) []string {
	seen := make(map[string]bool, len(dst))
	for _, kv := range dst {
		if k, _, ok := strings.Cut(kv, "="); ok {
			seen[k] = true
		}
	}
	for _, kv := range src {
		k, _, ok := strings.Cut(kv, "=")
		if ok && seen[k] {
			continue
		}
		dst = append(dst, kv)
	}
	return dst
}
