// Code generated by pluginsgen (charly box generate-plugins). DO NOT EDIT.
//
// One registerCompiledPlugin() call per plugin candy named in charly.yml
// `compiled_plugins:`. Regenerated by `task build:charly` before `go build`; the
// matching `use` directives land in the repo-root go.work. Edit charly.yml's
// compiled_plugins and re-run the generator, never this file.
package main

import (
	cp_plugin_addr "github.com/opencharly/charly/candy/plugin-addr"
	cp_plugin_agent "github.com/opencharly/charly/candy/plugin-agent"
	cp_plugin_build "github.com/opencharly/charly/candy/plugin-build"
	cp_plugin_builder "github.com/opencharly/charly/candy/plugin-builder"
	cp_plugin_candy_kind "github.com/opencharly/charly/candy/plugin-candy-kind"
	cp_plugin_command "github.com/opencharly/charly/candy/plugin-command"
	cp_plugin_distro "github.com/opencharly/charly/candy/plugin-distro"
	cp_plugin_dns "github.com/opencharly/charly/candy/plugin-dns"
	cp_plugin_egress "github.com/opencharly/charly/candy/plugin-egress"
	cp_plugin_enc "github.com/opencharly/charly/candy/plugin-enc"
	cp_plugin_example "github.com/opencharly/charly/candy/plugin-example"
	cp_plugin_example_bootstrap "github.com/opencharly/charly/candy/plugin-example-bootstrap"
	cp_plugin_example_command "github.com/opencharly/charly/candy/plugin-example-command"
	cp_plugin_example_external "github.com/opencharly/charly/candy/plugin-example-external"
	cp_plugin_examplerunverb "github.com/opencharly/charly/candy/plugin-examplerunverb"
	cp_plugin_file "github.com/opencharly/charly/candy/plugin-file"
	cp_plugin_gpu "github.com/opencharly/charly/candy/plugin-gpu"
	cp_plugin_group "github.com/opencharly/charly/candy/plugin-group"
	cp_plugin_http "github.com/opencharly/charly/candy/plugin-http"
	cp_plugin_init "github.com/opencharly/charly/candy/plugin-init"
	cp_plugin_installstep "github.com/opencharly/charly/candy/plugin-installstep"
	cp_plugin_interface "github.com/opencharly/charly/candy/plugin-interface"
	cp_plugin_k8sgen "github.com/opencharly/charly/candy/plugin-k8sgen"
	cp_plugin_kernel_param "github.com/opencharly/charly/candy/plugin-kernel-param"
	cp_plugin_matching "github.com/opencharly/charly/candy/plugin-matching"
	cp_plugin_migrate "github.com/opencharly/charly/candy/plugin-migrate"
	cp_plugin_module "github.com/opencharly/charly/candy/plugin-module"
	cp_plugin_mount "github.com/opencharly/charly/candy/plugin-mount"
	cp_plugin_package "github.com/opencharly/charly/candy/plugin-package"
	cp_plugin_package_group "github.com/opencharly/charly/candy/plugin-package-group"
	cp_plugin_port "github.com/opencharly/charly/candy/plugin-port"
	cp_plugin_preempt "github.com/opencharly/charly/candy/plugin-preempt"
	cp_plugin_process "github.com/opencharly/charly/candy/plugin-process"
	cp_plugin_resource "github.com/opencharly/charly/candy/plugin-resource"
	cp_plugin_service "github.com/opencharly/charly/candy/plugin-service"
	cp_plugin_sidecar "github.com/opencharly/charly/candy/plugin-sidecar"
	cp_plugin_substrate "github.com/opencharly/charly/candy/plugin-substrate"
	cp_plugin_target "github.com/opencharly/charly/candy/plugin-target"
	cp_plugin_tunnel "github.com/opencharly/charly/candy/plugin-tunnel"
	cp_plugin_unix_group "github.com/opencharly/charly/candy/plugin-unix-group"
	cp_plugin_user "github.com/opencharly/charly/candy/plugin-user"
)

func init() {
	registerCompiledPlugin(cp_plugin_example.NewProvider(), cp_plugin_example.NewMeta())
	registerCompiledPlugin(cp_plugin_example_external.NewProvider(), cp_plugin_example_external.NewMeta())
	registerCompiledPlugin(cp_plugin_example_command.NewProvider(), cp_plugin_example_command.NewMeta())
	registerCompiledPlugin(cp_plugin_example_bootstrap.NewProvider(), cp_plugin_example_bootstrap.NewMeta())
	registerCompiledPlugin(cp_plugin_egress.NewProvider(), cp_plugin_egress.NewMeta())
	registerCompiledPlugin(cp_plugin_k8sgen.NewProvider(), cp_plugin_k8sgen.NewMeta())
	registerCompiledPlugin(cp_plugin_gpu.NewProvider(), cp_plugin_gpu.NewMeta())
	registerCompiledPlugin(cp_plugin_preempt.NewProvider(), cp_plugin_preempt.NewMeta())
	registerCompiledPlugin(cp_plugin_enc.NewProvider(), cp_plugin_enc.NewMeta())
	registerCompiledCheckVerb(cp_plugin_port.NewCheckVerb(), cp_plugin_port.NewMeta())
	registerCompiledCheckVerb(cp_plugin_process.NewCheckVerb(), cp_plugin_process.NewMeta())
	registerCompiledCheckVerb(cp_plugin_interface.NewCheckVerb(), cp_plugin_interface.NewMeta())
	registerCompiledCheckVerb(cp_plugin_addr.NewCheckVerb(), cp_plugin_addr.NewMeta())
	registerCompiledCheckVerb(cp_plugin_dns.NewCheckVerb(), cp_plugin_dns.NewMeta())
	registerCompiledCheckVerb(cp_plugin_examplerunverb.NewCheckVerb(), cp_plugin_examplerunverb.NewMeta())
	registerCompiledPlugin(cp_plugin_matching.NewProvider(), cp_plugin_matching.NewMeta())
	registerCompiledCheckVerb(cp_plugin_http.NewCheckVerb(), cp_plugin_http.NewMeta())
	registerCompiledCheckVerb(cp_plugin_kernel_param.NewCheckVerb(), cp_plugin_kernel_param.NewMeta())
	registerCompiledCheckVerb(cp_plugin_mount.NewCheckVerb(), cp_plugin_mount.NewMeta())
	registerCompiledCheckVerb(cp_plugin_user.NewCheckVerb(), cp_plugin_user.NewMeta())
	registerCompiledCheckVerb(cp_plugin_unix_group.NewCheckVerb(), cp_plugin_unix_group.NewMeta())
	registerCompiledCheckVerb(cp_plugin_file.NewCheckVerb(), cp_plugin_file.NewMeta())
	registerCompiledCheckVerb(cp_plugin_command.NewCheckVerb(), cp_plugin_command.NewMeta())
	registerCompiledCheckVerb(cp_plugin_service.NewCheckVerb(), cp_plugin_service.NewMeta())
	registerCompiledCheckVerb(cp_plugin_package.NewCheckVerb(), cp_plugin_package.NewMeta())
	registerCompiledPlugin(cp_plugin_init.NewProvider(), cp_plugin_init.NewMeta())
	registerCompiledPlugin(cp_plugin_agent.NewProvider(), cp_plugin_agent.NewMeta())
	registerCompiledPlugin(cp_plugin_builder.NewProvider(), cp_plugin_builder.NewMeta())
	registerCompiledPlugin(cp_plugin_distro.NewProvider(), cp_plugin_distro.NewMeta())
	registerCompiledPlugin(cp_plugin_module.NewProvider(), cp_plugin_module.NewMeta())
	registerCompiledPlugin(cp_plugin_package_group.NewProvider(), cp_plugin_package_group.NewMeta())
	registerCompiledPlugin(cp_plugin_resource.NewProvider(), cp_plugin_resource.NewMeta())
	registerCompiledPlugin(cp_plugin_sidecar.NewProvider(), cp_plugin_sidecar.NewMeta())
	registerCompiledPlugin(cp_plugin_target.NewProvider(), cp_plugin_target.NewMeta())
	registerCompiledPlugin(cp_plugin_group.NewProvider(), cp_plugin_group.NewMeta())
	registerCompiledPlugin(cp_plugin_substrate.NewProvider(), cp_plugin_substrate.NewMeta())
	registerCompiledPlugin(cp_plugin_candy_kind.NewProvider(), cp_plugin_candy_kind.NewMeta())
	registerCompiledPlugin(cp_plugin_build.NewProvider(), cp_plugin_build.NewMeta())
	registerCompiledPlugin(cp_plugin_installstep.NewProvider(), cp_plugin_installstep.NewMeta())
	registerCompiledPlugin(cp_plugin_tunnel.NewProvider(), cp_plugin_tunnel.NewMeta())
	registerCompiledPlugin(cp_plugin_migrate.NewProvider(), cp_plugin_migrate.NewMeta())
}
