package main

// reserved_registry.go — the reserved-word ⇄ Go-handler registry + the startup
// BIJECTION gate. (The plain name `registry.go` is taken by the OCI remote-image
// module, so this file carries the reserved-word registry.) The reserved
// vocabulary is CUE-derived (charly/spec, regenerated by `task cue:gen` from
// sdk/schema/*.cue); this file is the SINGLE place that proves every
// CUE-declared reserved word has exactly one Go handler and vice versa — so a
// kind/verb can never be added to the schema without a handler, nor a handler
// kept after its word is dropped. The init() panics (fail-fast at process start,
// mirroring registerCueKind / mustCalVer); the same checks run as
// TestReservedWordRegistry_* (which also proves the gate FAILS when a handler is
// missing).
//
// It also hosts the CUE-derived membership SETS (below) — the loader's SINGLE
// reserved-word classification source: kind words, resource kinds, step
// keywords, authored #Op fields, and doc directives, each a set view of a
// spec.* slice regenerated by `task cue:gen` from sdk/schema/*.cue. Every loader
// consumer reads these; no hand-maintained parallel vocab list exists.

import (
	"fmt"
	"sort"

	"github.com/opencharly/sdk/spec"
)

// setFromSlice builds an O(1) membership set from a CUE-derived vocabulary slice.
func setFromSlice(words []string) map[string]bool {
	m := make(map[string]bool, len(words))
	for _, w := range words {
		m[w] = true
	}
	return m
}

// CUE-derived membership sets — the SINGLE source for the loader's reserved-word
// classification. Each is a set view of a spec.* slice generated by `task cue:gen`
// from sdk/schema/*.cue. NEVER hand-edit a parallel copy; change the schema and
// regenerate.
var (
	// kindWordSet — the authoring KIND vocabulary (#Node arms). Replaces the hand
	// kindKeys/kindKeysSet (unified.go) + nodeEntityKinds (node_parse.go).
	kindWordSet = setFromSlice(spec.KindWords)
	// resourceKindSet — the DEPLOYABLE subset that nests sub-entity children
	// (#ResourceKind). Replaces the hand nodeResourceKinds + node_normalize.go's
	// inline resource-child switch.
	resourceKindSet = setFromSlice(spec.ResourceKinds)
	// authoredOpFieldSet — the AUTHORED #Op field vocabulary (builtin verbs +
	// shared step modifiers, minus the never-authored internal fields). The
	// parse-time desugar (node_desugar.go) classifies a step key against it:
	// anything outside this set (and the intent keywords) is a plugin-verb
	// sugar key.
	authoredOpFieldSet = setFromSlice(spec.AuthoringVerbs)
	// docDirectiveSet — the reserved DOCUMENT directives (#NodeDoc). Replaces the
	// hand docDirectiveKeys (unified.go) + nodeDocDirectives (node_parse.go).
	docDirectiveSet = setFromSlice(spec.DocDirectives)
)

// ---------------------------------------------------------------------------
// Reserved-word ⇄ handler registry + the bijection gate.
// ---------------------------------------------------------------------------

// The kind decode dispatch + the kind⇄def bijection now live on the KindProviders
// (each in its own dedicated provider file) — folded onto the providers in C2 (R3),
// replacing the former hand-maintained handler map + its bijection gate.
// checkKindProviderBijection runs in registry_bootstrap.go's init() (the ONE built-in
// registration site), after all provider registration.

// internalOnlyVerbs are #OpVerb members that are NEVER authored: the generic
// `plugin` dispatcher is the desugar's rewrite TARGET (every `<word>: <input>`
// sugar key becomes plugin/plugin_input internally), so it is deliberately
// excluded from spec.AuthoringVerbs while remaining a real dispatch verb.
var internalOnlyVerbs = map[string]bool{"plugin": true}

// checkVerbBijection verifies the package-main VerbCatalog dispatch table and the
// CUE verb vocabulary (spec.OpVerbs) are in exact bijection, and that every
// AUTHORED verb is also a member of the authorable Op vocabulary
// (spec.AuthoringVerbs) — the internal-only verbs are exempt by design.
func checkVerbBijection(catalog map[string]spec.VerbSpec, verbs, authoring []string) error {
	want := setFromSlice(verbs)
	auth := setFromSlice(authoring)
	var missing, extra, notAuthorable []string
	for v := range want {
		if _, ok := catalog[v]; !ok {
			missing = append(missing, v)
		}
		if !auth[v] && !internalOnlyVerbs[v] {
			notAuthorable = append(notAuthorable, v)
		}
	}
	for v := range catalog {
		if !want[v] {
			extra = append(extra, v)
		}
	}
	sort.Strings(missing)
	sort.Strings(extra)
	sort.Strings(notAuthorable)
	if len(missing) > 0 || len(extra) > 0 || len(notAuthorable) > 0 {
		return fmt.Errorf("reserved-word registry: verb bijection broken — verbs in spec.OpVerbs with no VerbCatalog handler: %v; VerbCatalog keys not in spec.OpVerbs: %v; verbs not in spec.AuthoringVerbs: %v", missing, extra, notAuthorable)
	}
	return nil
}

// init is the startup verb-bijection gate. It panics unless every reserved word in
// the CUE vocabulary has exactly one Go handler and vice versa — a fail-fast that
// makes a schema/handler divergence impossible to ship.
func init() {
	if err := checkVerbBijection(spec.VerbCatalog, spec.OpVerbs, spec.AuthoringVerbs); err != nil {
		panic(err)
	}
}
