package main

// tunnel.go is the RESOLUTION half of the tunnel subsystem. The EXECUTION leg (the
// tailscale serve/funnel commands + the cloudflared tunnel lifecycle) was externalized
// to candy/plugin-tunnel (verb:tunnel) — the C16b core-externalization cutover. The
// former core dispatch adapter (forwarding start/stop/setup over verb:tunnel via the
// provider registry) is DELETED (Cutover B
// unit 2 remove-verb completion) — its last caller was podRemoveCmd.Run()'s tunnel
// teardown, and that now happens PLUGIN-side (candy/plugin-pod's RemoveCmd.Run() /
// remove_tunnel.go), mirroring how candy/plugin-deploy-pod's podStart/podStop already
// drive verb:tunnel directly via InvokeProvider for the start/stop legs, and how
// candy/plugin-deploy-pod's own setup path already invokes verb:tunnel's `setup` method
// directly. So EVERY tunnel EXECUTION leg (start/stop/setup) is now plugin-driven with
// zero core-side dispatch — core keeps ONLY the PURE, execution-free RESOLUTION
// surface, still needed beyond the deploy path (like GenerateK8sKustomize):
//
//   - the wire types TunnelConfig / TunnelPort — CUE-SOURCED in sdk/schema/tunnel.cue
//     (spec.TunnelConfig / spec.TunnelPort, generated by task cue:gen) and ALIASED here;
//     the resolution builds them and the various pod-config-* seams marshal them across
//     the process boundary to the plugin that resolved them (the json keys are the wire
//     contract), and the deploykit quadlet emitter consumes QuadletConfig.Tunnel (the
//     ExecStartPost=tailscale serve emission + the SchemeTarget/TailscaleFlag/IsTCPFamily
//     command builders + the TunnelPort.Backend() default all moved to sdk/deploykit /
//     sdk/spec with the config-write mechanism in P11). The former hand-written wire
//     mirror was deleted when the wire-type mandate was repaired (P11);
//   - the resolution ResolveTunnelConfig / TunnelConfigFromMetadata (and their pure
//     helpers parseHostPorts / buildPortMapping / resolveProto) — turn a charly.yml
//     TunnelYAML (or image-label metadata) into a ready-to-execute TunnelConfig. The
//     resolution logic itself is a pure Mechanism (no host I/O, no globals) and moved
//     to sdk/deploykit/tunnel_resolve.go (FLOOR-SLIM mechanical batch). Every
//     charly-side caller (box_inspect_overlay.go, host_build_pod_config_seams.go,
//     pod_lifecycle_resolve.go) calls deploykit.ResolveTunnelConfig /
//     deploykit.TunnelConfigFromMetadata directly — NO alias re-export here
//     (NO-NEW-ALIASES: an alias is a mislocated call site, never a legitimate
//     landing spot).
//
// ValidPublicPorts (a stale "allowed public serve ports" table) was DELETED in the same
// batch — it had ZERO callers anywhere in the tree; the public-port ALLOW decision is
// actually made by TunnelYAML.Public (the authored public/private port sets resolved
// above), not by a fixed allowlist.

import (
	"github.com/opencharly/sdk/spec"
)

// TunnelConfig / TunnelPort are the RESOLVED tunnel WIRE types — CUE-SOURCED in
// sdk/schema/tunnel.cue (single source per the SDD wire-type mandate) and generated
// into spec by task cue:gen. They are ALIASED into package main here (the zero-churn
// repoint): every core call site (quadlet emitter, the pod-config-* seams' wire
// marshaling, resolution helpers) compiles unchanged against the spec types. The former hand-written mirror
// (a pre-existing wire-mandate violation) was DELETED in the P11 relocation. The
// TunnelPort.Backend() default lives in spec (sdk/spec/tunnel_methods.go) beside the type.
type (
	TunnelPort   = spec.TunnelPort
	TunnelConfig = spec.TunnelConfig
)

// ResolveTunnelConfig / TunnelConfigFromMetadata (and their pure helpers
// parseHostPorts / buildPortMapping / resolveProto) now live entirely in
// sdk/deploykit/tunnel_resolve.go (FLOOR-SLIM mechanical batch) — see the file
// header. Every charly-side caller (box_inspect_overlay.go,
// host_build_pod_config_seams.go, pod_lifecycle_resolve.go) calls
// deploykit.ResolveTunnelConfig / deploykit.TunnelConfigFromMetadata directly
// (NO-NEW-ALIASES: a declaration-form `var X = deploykit.Y` re-export here
// would just be the mislocated call site wearing a new hat).
