package main

// tunnel.go is the RESOLUTION half of the tunnel subsystem. The EXECUTION leg (the
// tailscale serve/funnel commands + the cloudflared tunnel lifecycle) was externalized
// to candy/plugin-tunnel (verb:tunnel) — the C16b core-externalization cutover. The
// former core dispatch adapter (forwarding start/stop/setup over verb:tunnel via the
// provider registry) is DELETED (Cutover B
// unit 2 remove-verb completion) — its last caller was podRemoveCmd.Run()'s tunnel
// teardown, and that now happens PLUGIN-side (candy/plugin-pod's RemoveCmd.Run() /
// remove_tunnel.go), mirroring how candy/plugin-deploy-pod's podStart/podStop already
// drive verb:tunnel directly via InvokeProvider for the start/stop legs, and how
// candy/plugin-deploy-pod's own setup path already invokes verb:tunnel's `setup` method
// directly. So EVERY tunnel EXECUTION leg (start/stop/setup) is now plugin-driven with
// zero core-side dispatch — core keeps ONLY the PURE, execution-free RESOLUTION
// surface, still needed beyond the deploy path (like GenerateK8sKustomize):
//
//   - the wire types TunnelConfig / TunnelPort — CUE-SOURCED in sdk/schema/tunnel.cue
//     (spec.TunnelConfig / spec.TunnelPort, generated by task cue:gen) and ALIASED here;
//     the resolution builds them and the various pod-config-* seams marshal them across
//     the process boundary to the plugin that resolved them (the json keys are the wire
//     contract), and the deploykit quadlet emitter consumes QuadletConfig.Tunnel (the
//     ExecStartPost=tailscale serve emission + the SchemeTarget/TailscaleFlag/IsTCPFamily
//     command builders + the TunnelPort.Backend() default all moved to sdk/deploykit /
//     sdk/spec with the config-write mechanism in P11). The former hand-written wire
//     mirror was deleted when the wire-type mandate was repaired (P11);
//   - ValidPublicPorts — the allowed public serve ports, consulted by the resolution to
//     validate a tunnel's public ports (the cloudflared config-path computation moved along
//     with BoxConfigSetupCmd's orchestration to candy/plugin-deploy-pod's own tunnelConfigPath,
//     P13-KERNEL direction-flip — no host-side copy needed anymore);
//   - the resolution ResolveTunnelConfig / TunnelConfigFromMetadata / parseHostPorts /
//     buildPortMapping / resolveProto — turn a charly.yml TunnelYAML (or image-label
//     metadata) into a ready-to-execute TunnelConfig, still consumed by the
//     pod-config-container-tunnel / pod-config-tunnel-resolve host-build seams.

import (
	"fmt"
	"os"
	"strconv"

	"github.com/opencharly/sdk/spec"
)

// TunnelConfig / TunnelPort are the RESOLVED tunnel WIRE types — CUE-SOURCED in
// sdk/schema/tunnel.cue (single source per the SDD wire-type mandate) and generated
// into spec by task cue:gen. They are ALIASED into package main here (the zero-churn
// repoint): every core call site (quadlet emitter, the pod-config-* seams' wire
// marshaling, resolution helpers) compiles unchanged against the spec types. The former hand-written mirror
// (a pre-existing wire-mandate violation) was DELETED in the P11 relocation. The
// TunnelPort.Backend() default lives in spec (sdk/spec/tunnel_methods.go) beside the type.
type (
	TunnelPort   = spec.TunnelPort
	TunnelConfig = spec.TunnelConfig
)

// ValidPublicPorts are the allowed external ports for Tailscale public access.
var ValidPublicPorts = map[int]bool{443: true, 8443: true, 10000: true}

// parseHostPorts extracts host-side ports from image port mappings via the
// canonical ParsePortMapping. Unparseable entries are reported on stderr —
// silent skipping was the root cause of an unrelated bug where tunnel rules
// vanished without a diagnostic.
func parseHostPorts(boxPorts []string) []int {
	var result []int
	for _, mapping := range boxPorts {
		p, ok := ParsePortMapping(mapping)
		if !ok {
			fmt.Fprintf(os.Stderr,
				"Warning: ignoring unparseable port mapping %q (expected forms: \"P\", \"H:C\", \"IP:H:C\")\n",
				mapping)
			continue
		}
		result = append(result, p.Host)
	}
	return result
}

// buildPortMapping builds a host→container port map from image port mappings.
// Same loud-failure policy as parseHostPorts — see comment above.
func buildPortMapping(boxPorts []string) map[int]int {
	m := make(map[int]int, len(boxPorts))
	for _, mapping := range boxPorts {
		p, ok := ParsePortMapping(mapping)
		if !ok {
			fmt.Fprintf(os.Stderr,
				"Warning: ignoring unparseable port mapping %q (expected forms: \"P\", \"H:C\", \"IP:H:C\")\n",
				mapping)
			continue
		}
		m[p.Host] = p.Container
	}
	return m
}

// resolveProto returns the backend scheme for a container port, defaulting to "http".
// portProtos is string-keyed (the OCI-label wire form, P2B reshape) — index by the port as a string.
func resolveProto(containerPort int, portProtos map[string]string) string {
	if portProtos != nil {
		if pp, ok := portProtos[strconv.Itoa(containerPort)]; ok {
			return pp
		}
	}
	return "http"
}

// ResolveTunnelConfig resolves a TunnelYAML into a TunnelConfig with defaults applied.
// portProtos maps container port -> protocol ("http" or "tcp") from candy PortSpec data.
// boxPorts is the list of image port mappings (e.g. "18789:18789", "443:18789").
func ResolveTunnelConfig(t *spec.TunnelYAML, boxName string, dns string, _ map[string]spec.CandyReader, _ []string, portProtos map[string]string, boxPorts []string) *TunnelConfig {
	if t == nil {
		return nil
	}

	cfg := &TunnelConfig{
		Provider: t.Provider,
		BoxName:  boxName,
	}

	hostPorts := parseHostPorts(boxPorts)
	hostToContainer := buildPortMapping(boxPorts)

	// Determine public set
	publicSet := make(map[int]bool)
	publicHostnames := make(map[int]string)
	if t.Public.All {
		for _, p := range hostPorts {
			publicSet[p] = true
		}
	}
	for _, p := range t.Public.Ports {
		publicSet[p] = true
	}
	for p, h := range t.Public.PortMap {
		publicSet[p] = true
		publicHostnames[p] = h
	}

	// Determine private set ("all" means all remaining ports not already public)
	privateSet := make(map[int]bool)
	if t.Private.All {
		for _, p := range hostPorts {
			if !publicSet[p] {
				privateSet[p] = true
			}
		}
	}
	for _, p := range t.Private.Ports {
		privateSet[p] = true
	}

	// Build TunnelPort slice (ordered by image port order)
	for _, hp := range hostPorts {
		if !publicSet[hp] && !privateSet[hp] {
			continue // port not tunneled
		}
		cp := hp
		if c, ok := hostToContainer[hp]; ok {
			cp = c
		}
		proto := resolveProto(cp, portProtos)
		cfg.Ports = append(cfg.Ports, TunnelPort{
			Port:        hp,
			BackendPort: hp,
			Protocol:    proto,
			Public:      publicSet[hp],
			Hostname:    publicHostnames[hp],
		})
	}

	// Cloudflare defaults
	if cfg.Provider == "cloudflare" {
		cfg.TunnelName = t.Tunnel
		if cfg.TunnelName == "" {
			cfg.TunnelName = "charly-" + boxName
		}
		cfg.Hostname = dns
	}

	return cfg
}

// TunnelConfigFromMetadata creates a TunnelConfig from image label metadata.
// Unlike ResolveTunnelConfig, this doesn't need candy access since the tunnel
// configuration is already stored in the label.
func TunnelConfigFromMetadata(meta *BoxMetadata) *TunnelConfig {
	if meta == nil || meta.Tunnel == nil {
		return nil
	}

	t := meta.Tunnel
	cfg := &TunnelConfig{
		Provider: t.Provider,
		BoxName:  meta.Box,
	}

	hostPorts := parseHostPorts(meta.Port)
	hostToContainer := buildPortMapping(meta.Port)

	// Determine public set
	publicSet := make(map[int]bool)
	publicHostnames := make(map[int]string)
	if t.Public.All {
		for _, p := range hostPorts {
			publicSet[p] = true
		}
	}
	for _, p := range t.Public.Ports {
		publicSet[p] = true
	}
	for p, h := range t.Public.PortMap {
		publicSet[p] = true
		publicHostnames[p] = h
	}

	// Determine private set
	privateSet := make(map[int]bool)
	if t.Private.All {
		for _, p := range hostPorts {
			if !publicSet[p] {
				privateSet[p] = true
			}
		}
	}
	for _, p := range t.Private.Ports {
		privateSet[p] = true
	}

	// Build TunnelPort slice
	for _, hp := range hostPorts {
		if !publicSet[hp] && !privateSet[hp] {
			continue
		}
		cp := hp
		if c, ok := hostToContainer[hp]; ok {
			cp = c
		}
		proto := resolveProto(cp, meta.PortProto)
		cfg.Ports = append(cfg.Ports, TunnelPort{
			Port:        hp,
			BackendPort: hp,
			Protocol:    proto,
			Public:      publicSet[hp],
			Hostname:    publicHostnames[hp],
		})
	}

	// Cloudflare defaults
	if cfg.Provider == "cloudflare" {
		cfg.TunnelName = t.Tunnel
		if cfg.TunnelName == "" {
			cfg.TunnelName = "charly-" + meta.Box
		}
		cfg.Hostname = meta.DNS
	}

	return cfg
}
