#!/usr/bin/env bash
# check-generated-clean.sh — classify the TRACKED files that pluginsgen + the workspace
# go build REWRITE, so a nominally successful build cannot leave an unexplained dirty tree.
#
# Run with cwd at the charly repo root (scripts/bootstrap-charly.sh does). Prints one
# `<class> <path>` line per file with `--list`, and enforces them otherwise.
#
# The classes are split by WHAT each file is DERIVED FROM, because that alone decides
# whether drift is fixable in this repository:
#
#   inconsistent  derived from TRACKED inputs — charly.yml's `compiled_plugins:`, the
#                 go.mod pins, and the committed workspace. A diff therefore means THIS
#                 CHECKOUT is internally inconsistent (a hand-edit, or a generator change
#                 that was never regenerated). The remedy is to review and commit HERE, so
#                 it is a hard failure.
#
#   upstream      `charly/plugins_refs_generated.go` is a projection of a source this
#                 checkout does NOT pin: pluginsgen's index fetches each corpus repo at
#                 "HEAD" — its default branch (internal/pluginsgen/main.go, collectWordRefs),
#                 deliberately, because the word->ref FACT lives in the plugin repos, and a
#                 --dev-plugin override re-points its read at a local checkout. A diff
#                 therefore means some OTHER tree moved; nothing here is wrong, and in a
#                 detached umbrella submodule checkout the review-and-commit remedy is
#                 forbidden. So it is NAMED and the tracked file is RESTORED: the build keeps
#                 the fresh index (the artifact under test is unaffected), and the tree stays
#                 clean.
#
#                 Restoring is safe by contract, not by assumption: the file's own header
#                 is "Code generated by charly/internal/pluginsgen ... DO NOT EDIT", so the
#                 build is its only legitimate writer. (The build/CI drift gate for it is
#                 TestPluginsRefsIndexSound, which is well-defined against a MOVING
#                 upstream — see charly/internal/pluginsgen/main_test.go.)
#
# Exit: 0 = clean, or upstream-only drift restored; 1 = an inconsistent file is stale;
#       2 = not inside a git worktree (there is no lineage to compare against).
set -euo pipefail

# The ONE canonical list. TestGeneratedCleanScript (charly/generated_clean_script_test.go)
# reads it back with --list instead of restating it, and fails if an entry is dropped.
CLASSES=(
  "inconsistent go.work"
  "inconsistent go.work.sum"
  "inconsistent charly/plugins_generated.go"
  "upstream charly/plugins_refs_generated.go"
)

if [ "${1:-}" = "--list" ]; then
  printf '%s\n' "${CLASSES[@]}"
  exit 0
fi
if [ $# -gt 0 ]; then
  echo "check-generated-clean: unknown argument: $1" >&2
  exit 2
fi

if ! git rev-parse --git-dir >/dev/null 2>&1; then
  echo "check-generated-clean: not inside a git worktree — a source export has no lineage to compare against" >&2
  exit 2
fi

status=0
for entry in "${CLASSES[@]}"; do
  class="${entry%% *}"
  path="${entry#* }"
  # `if` rather than `&& continue`: under `set -e` a bare `git diff --quiet && continue`
  # exits the script on the DIRTY case — the exact case this guard exists to handle.
  if git diff --quiet -- "$path"; then
    continue
  fi
  case "$class" in
    inconsistent)
      echo "check-generated-clean: $path is STALE — it is derived from TRACKED inputs, so this checkout is inconsistent." >&2
      echo "Review and commit it, then re-run scripts/bootstrap-charly.sh." >&2
      git diff -- "$path" >&2
      status=1
      ;;
    upstream)
      echo "check-generated-clean: NOTICE — $path differs because it was indexed from a source this checkout does not pin" >&2
      echo "check-generated-clean:   (a corpus plugin's default branch, or a --dev-plugin local checkout); restoring the tracked file." >&2
      git checkout -- "$path"
      ;;
    *)
      echo "check-generated-clean: unknown class $class for $path" >&2
      exit 2
      ;;
  esac
done
exit "$status"
