// Code generated by `task cue:gen` (charly/internal/schemagen); DO NOT EDIT.
//
// The HEAD schema CalVer + the oldest migratable floor, derived from
// charly/schema/version.cue. kit.LatestSchemaVersion()/SchemaFloor() parse
// these; never hand-edit — regenerate with `task cue:gen`.

package spec

// SchemaVersion is the HEAD schema CalVer (charly/schema/version.cue #SchemaVersion).
const SchemaVersion = "2026.174.1100"

// SchemaFloor is the oldest schema version `charly migrate` can migrate FROM
// (charly/schema/version.cue #SchemaFloor).
const SchemaFloor = "2026.174.1100"
